language: objective-c
 
xcode_project: Nosh.xcodeproj
xcode_scheme: Nosh
osx_image: xcode7.3

before_install: 
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose

script:
  - xctool -project Nosh.xcodeproj -scheme Nosh build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
